import type { Task } from '@/types/task.types'

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Finish dashboard',
    description: 'Wrap up the remaining UI details.',
    status: 'todo',
    priority: 'high',
    owner: 'Adrian Nistor',
    dueDate: '2026-04-02',
    createdAt: '2026-03-24',
    isMock: true,
  },
  {
    id: 'task-002',
    title: 'Review API states',
    description: 'Check loading, error, and empty flows.',
    status: 'todo',
    priority: 'medium',
    owner: 'Ioana Popescu',
    dueDate: '2026-04-07',
    createdAt: '2026-03-25',
    isMock: true,
  },
  {
    id: 'task-003',
    title: 'Centralise types',
    description: 'Move shared types into one place.',
    status: 'in_progress',
    priority: 'medium',
    owner: 'Ioana Popescu',
    dueDate: '2026-04-05',
    createdAt: '2026-03-26',
    isMock: true,
  },
  {
    id: 'task-004',
    title: 'Polish task details',
    description: 'Tighten spacing and hierarchy in the details panel.',
    status: 'in_progress',
    priority: 'high',
    owner: 'Adrian Nistor',
    dueDate: '2026-04-01',
    createdAt: '2026-03-27',
    isMock: true,
  },
  {
    id: 'task-005',
    title: 'Finalize analytics event mapping',
    description: 'Finish the event map for the main task actions.',
    status: 'done',
    priority: 'high',
    owner: 'Mihai Georgescu',
    dueDate: '2026-03-28',
    createdAt: '2026-03-20',
    isMock: true,
  },
  {
    id: 'task-006',
    title: 'Write README notes',
    description: 'Add setup and architecture notes.',
    status: 'done',
    priority: 'low',
    owner: 'Mihai Georgescu',
    dueDate: '2026-03-30',
    createdAt: '2026-03-22',
    isMock: true,
  },
]
